name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Move to Subpath Folder
        run: |
          mkdir aurora
          cp index.html aurora/
          cp -r static aurora/

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.4.3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: aurora
