name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master # or main, depending on your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install Dependencies (if you have any)
        run: npm install # or yarn install, depending on your preference

      - name: Build (if you have a build script)
        run: npm run build # adjust this if you have a different build command

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: dist # The folder the action should deploy. Change to the folder where your build command puts its output, if you have one.
